### ISSUE TITLE
Crash after resume from hibernation on Windows

### ISSUE THREAD

**Issue by Vertikar** [peted-davis/WeatherFlow_PyConsole#2]
I know you're not currently supporting Windows, so happy for you to close this as wontfix immediately, but after waking my PC this morning it seems that it crashed.
Maybe due to the network not being ready immediately, as this was stored on a network drive, but it looks like it didn't handle that very well.
Logs below:
```
2018-09-15 17:51:57+1000 [-] Starting factory <__main__.WeatherFlowClientFactory object at 0x000001FC1DB0F128>
[ERROR  ] [Image       ] Error reading file Icons/Sun/45.7.png
[ERROR  ] [Image       ] Error reading file Icons/Sun/45.7.png
[ERROR  ] [Image       ] Error reading file Icons/Moon/Waxing_40.png
[ERROR  ] [Image       ] Error reading file Icons/Moon/Waxing_40.png
[INFO   ] [Base        ] Leaving application in progress...
[INFO   ] [Support     ] Stopping twisted threads
[INFO   ] [Support     ] Shutting down twisted reactor
2018-09-16 09:20:14+1000 [-] Traceback (most recent call last):
2018-09-16 09:20:14+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
2018-09-16 09:20:14+1000 [-]     (self._dns_host, self.port), self.timeout, **extra_kw)
2018-09-16 09:20:14+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\util\connection.py", line 56, in create_connection
2018-09-16 09:20:14+1000 [-]     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2018-09-16 09:20:14+1000 [-]   File "C:\Program Files\Python36\lib\socket.py", line 745, in getaddrinfo
2018-09-16 09:20:14+1000 [-]     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2018-09-16 09:20:14+1000 [-] socket.gaierror: [Errno 11001] getaddrinfo failed
2018-09-16 09:20:14+1000 [-]
2018-09-16 09:20:14+1000 [-] During handling of the above exception, another exception occurred:
2018-09-16 09:20:14+1000 [-]
2018-09-16 09:20:14+1000 [-] Traceback (most recent call last):
2018-09-16 09:20:14+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
2018-09-16 09:20:14+1000 [-]     chunked=chunked)
2018-09-16 09:20:14+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
2018-09-16 09:20:15+1000 [-]     self._validate_conn(conn)
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
2018-09-16 09:20:15+1000 [-]     conn.connect()
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 314, in connect
2018-09-16 09:20:15+1000 [-]     conn = self._new_conn()
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
2018-09-16 09:20:15+1000 [-]     self, "Failed to establish a new connection: %s" % e)
2018-09-16 09:20:15+1000 [-] urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001FC1D588AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
2018-09-16 09:20:15+1000 [-]
2018-09-16 09:20:15+1000 [-] During handling of the above exception, another exception occurred:
2018-09-16 09:20:15+1000 [-]
2018-09-16 09:20:15+1000 [-] Traceback (most recent call last):
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 445, in send
2018-09-16 09:20:15+1000 [-]     timeout=timeout
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
2018-09-16 09:20:15+1000 [-]     _stacktrace=sys.exc_info()[2])
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\urllib3\util\retry.py", line 398, in increment
2018-09-16 09:20:15+1000 [-]     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2018-09-16 09:20:15+1000 [-] urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='swd.weatherflow.com', port=443): Max retries exceeded with url: /swd/rest/observations/device/15135?time_start=1537031954&time_end=1537053614&api_key=146e4f2c-adec-4244-b711-1aeca8f46a48 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FC1D588AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2018-09-16 09:20:15+1000 [-]
2018-09-16 09:20:15+1000 [-] During handling of the above exception, another exception occurred:
2018-09-16 09:20:15+1000 [-]
2018-09-16 09:20:15+1000 [-] Traceback (most recent call last):
2018-09-16 09:20:15+1000 [-]   File "main.py", line 1712, in <module>
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\kivy\app.py", line 826, in run
2018-09-16 09:20:15+1000 [-]     runTouchApp()
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\kivy\base.py", line 502, in runTouchApp
2018-09-16 09:20:15+1000 [-]     EventLoop.window.mainloop()
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
2018-09-16 09:20:15+1000 [-]     self._mainloop()
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
2018-09-16 09:20:15+1000 [-]     EventLoop.idle()
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\kivy\base.py", line 337, in idle
2018-09-16 09:20:15+1000 [-]     Clock.tick()
2018-09-16 09:20:15+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\kivy\clock.py", line 581, in tick
2018-09-16 09:20:16+1000 [-]     self._process_events()
2018-09-16 09:20:16+1000 [-]   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
2018-09-16 09:20:16+1000 [-]   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
2018-09-16 09:20:16+1000 [-]   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
2018-09-16 09:20:16+1000 [-]   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
2018-09-16 09:20:16+1000 [-]   File "main.py", line 1410, in Calc_SagerForecast
2018-09-16 09:20:16+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 72, in get
2018-09-16 09:20:16+1000 [-]     return request('get', url, params=params, **kwargs)
2018-09-16 09:20:16+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 58, in request
2018-09-16 09:20:16+1000 [-]     return session.request(method=method, url=url, **kwargs)
2018-09-16 09:20:16+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 512, in request
2018-09-16 09:20:16+1000 [-]     resp = self.send(prep, **send_kwargs)
2018-09-16 09:20:16+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 622, in send
2018-09-16 09:20:16+1000 [-]     r = adapter.send(request, **kwargs)
2018-09-16 09:20:16+1000 [-]   File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 513, in send
2018-09-16 09:20:16+1000 [-]     raise ConnectionError(e, request=request)
2018-09-16 09:20:16+1000 [-] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='swd.weatherflow.com', port=443): Max retries exceeded with url: /swd/rest/observations/device/15135?time_start=1537031954&time_end=1537053614&api_key=146e4f2c-adec-4244-b711-1aeca8f46a48 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FC1D588AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

```
H:\bin\apps\WeatherFlow_PyConsole-0.3-beta>
`

**Comment by peted-davis** [comment]
I've tried a few times to recreate this issue with no luck. For me the console recovers quite happily from hibernation, assuming you leave it for at least 1 minute to allow the websocket to reconnect. I imagine the issue for you is related to the network drive, and that not being available immediately. As you say, Windows is not the platform the console is designed for, so I am going to close this issue with no guarantee that I'll be able to find a fix in the future.
